# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Assemble Build"
  lane :assemble_build_release do
    properties = {
      "android.injected.signing.store.file" => "release.keystore",
      "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['KEY_PASSWORD']
    }
    gradle(task: "assemble", build_type: "Release", properties: properties, print_command: false)
  end

  desc "Run unit tests"
  lane :unit_tests do
    gradle(task: "ktlint")
    gradle(task: "lint")
    gradle(task: "test", build_type: "Debug")
  end

  desc "Submit a new Beta Build to Crashlytics"
  lane :deploy_to_crashlytics do
    assemble_build_release
    crashlytics(api_token: ENV['CRASHLYTICS_API_TOKEN'],
    build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
    apk_path: "app/build/outputs/apk/release/app-release.apk",
    notes_path: "release-notes.txt")
  end
end
